/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetallesCobro;
import modelo.Recepcionista;

/**
 *
 * @author Pareja 3
 */
public class CancelarReserva extends JFrame {

    /**
     * Creates new form CancelarReserva
     *
     * @param recepcionista
     * @param VAnterior
     */
    public CancelarReserva(Recepcionista recepcionista, JFrame VAnterior) {
        initComponents();

        this.recepcionista = recepcionista;
        this.VAnterior = VAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCancelarReserva = new javax.swing.JPanel();
        panelCancelarReservaPrincipal = new javax.swing.JPanel();
        panelCancelarReservaPrincipalListado = new javax.swing.JPanel();
        panelCancelarReservaListado = new javax.swing.JPanel();
        panelCancelarReservaBuscarCliente = new javax.swing.JPanel();
        panelCancelarReservaPrincipalBuscarCliente = new javax.swing.JPanel();
        panelCancelarReservaClienteDNI = new javax.swing.JPanel();
        fieldCancelarReservaDNICliente = new javax.swing.JTextField();
        panelCancelarReservaBttnBuscar = new javax.swing.JPanel();
        bttnCancelarReservaBuscar = new javax.swing.JButton();
        scrollPaneCancelarReserva = new javax.swing.JScrollPane();
        tableCancelarReservaReservasPendientes = new javax.swing.JTable();
        panelCancelarReservaOpciones = new javax.swing.JPanel();
        bttnCancelarReserva = new javax.swing.JButton();
        bttnCancelarReservaAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 350));

        panelCancelarReserva.setBackground(new java.awt.Color(102, 102, 102));
        panelCancelarReserva.setPreferredSize(new java.awt.Dimension(500, 350));

        panelCancelarReservaPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        panelCancelarReservaPrincipal.setAlignmentX(0.0F);
        panelCancelarReservaPrincipal.setAlignmentY(0.0F);
        panelCancelarReservaPrincipal.setLayout(new java.awt.BorderLayout());

        panelCancelarReservaPrincipalListado.setBackground(new java.awt.Color(153, 153, 153));
        panelCancelarReservaPrincipalListado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelCancelarReservaListado.setLayout(new java.awt.BorderLayout());

        panelCancelarReservaBuscarCliente.setBackground(new java.awt.Color(153, 153, 153));
        panelCancelarReservaBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCancelarReservaBuscarCliente.setPreferredSize(new java.awt.Dimension(454, 73));

        panelCancelarReservaPrincipalBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCancelarReservaPrincipalBuscarCliente.setPreferredSize(new java.awt.Dimension(454, 73));
        panelCancelarReservaPrincipalBuscarCliente.setLayout(new java.awt.BorderLayout());

        panelCancelarReservaClienteDNI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelCancelarReservaClienteDNI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelCancelarReservaClienteDNI.setLayout(new java.awt.BorderLayout());

        fieldCancelarReservaDNICliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldCancelarReservaDNICliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelCancelarReservaClienteDNI.add(fieldCancelarReservaDNICliente, java.awt.BorderLayout.CENTER);

        panelCancelarReservaPrincipalBuscarCliente.add(panelCancelarReservaClienteDNI, java.awt.BorderLayout.CENTER);

        bttnCancelarReservaBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnCancelarReservaBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_32.png"))); // NOI18N
        bttnCancelarReservaBuscar.setText("BUSCAR");
        bttnCancelarReservaBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnCancelarReservaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarReservaBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCancelarReservaBttnBuscarLayout = new javax.swing.GroupLayout(panelCancelarReservaBttnBuscar);
        panelCancelarReservaBttnBuscar.setLayout(panelCancelarReservaBttnBuscarLayout);
        panelCancelarReservaBttnBuscarLayout.setHorizontalGroup(
            panelCancelarReservaBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
            .addGroup(panelCancelarReservaBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCancelarReservaBttnBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bttnCancelarReservaBuscar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelCancelarReservaBttnBuscarLayout.setVerticalGroup(
            panelCancelarReservaBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(panelCancelarReservaBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCancelarReservaBttnBuscarLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(bttnCancelarReservaBuscar)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        panelCancelarReservaPrincipalBuscarCliente.add(panelCancelarReservaBttnBuscar, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout panelCancelarReservaBuscarClienteLayout = new javax.swing.GroupLayout(panelCancelarReservaBuscarCliente);
        panelCancelarReservaBuscarCliente.setLayout(panelCancelarReservaBuscarClienteLayout);
        panelCancelarReservaBuscarClienteLayout.setHorizontalGroup(
            panelCancelarReservaBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCancelarReservaPrincipalBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        panelCancelarReservaBuscarClienteLayout.setVerticalGroup(
            panelCancelarReservaBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCancelarReservaPrincipalBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        panelCancelarReservaListado.add(panelCancelarReservaBuscarCliente, java.awt.BorderLayout.NORTH);

        tableCancelarReservaReservasPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habitacion", "DNI", "Nombre", "Dias", "Importe", "Estado", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCancelarReservaReservasPendientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCancelarReservaReservasPendientes.getTableHeader().setReorderingAllowed(false);
        scrollPaneCancelarReserva.setViewportView(tableCancelarReservaReservasPendientes);
        if (tableCancelarReservaReservasPendientes.getColumnModel().getColumnCount() > 0) {
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(0).setResizable(false);
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(1).setResizable(false);
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(2).setResizable(false);
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(3).setResizable(false);
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(4).setResizable(false);
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(5).setResizable(false);
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(6).setResizable(false);
            tableCancelarReservaReservasPendientes.getColumnModel().getColumn(6).setPreferredWidth(0);
        }

        panelCancelarReservaListado.add(scrollPaneCancelarReserva, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelCancelarReservaPrincipalListadoLayout = new javax.swing.GroupLayout(panelCancelarReservaPrincipalListado);
        panelCancelarReservaPrincipalListado.setLayout(panelCancelarReservaPrincipalListadoLayout);
        panelCancelarReservaPrincipalListadoLayout.setHorizontalGroup(
            panelCancelarReservaPrincipalListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarReservaPrincipalListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCancelarReservaListado, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCancelarReservaPrincipalListadoLayout.setVerticalGroup(
            panelCancelarReservaPrincipalListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarReservaPrincipalListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCancelarReservaListado, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCancelarReservaPrincipal.add(panelCancelarReservaPrincipalListado, java.awt.BorderLayout.CENTER);

        panelCancelarReservaOpciones.setBackground(new java.awt.Color(153, 153, 153));
        panelCancelarReservaOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnCancelarReserva.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnCancelarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_reserva_32.png"))); // NOI18N
        bttnCancelarReserva.setText("Cancelar Reserva");
        bttnCancelarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarReservaActionPerformed(evt);
            }
        });

        bttnCancelarReservaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver_32.png"))); // NOI18N
        bttnCancelarReservaAtras.setText("Atrás");
        bttnCancelarReservaAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnCancelarReservaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarReservaAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCancelarReservaOpcionesLayout = new javax.swing.GroupLayout(panelCancelarReservaOpciones);
        panelCancelarReservaOpciones.setLayout(panelCancelarReservaOpcionesLayout);
        panelCancelarReservaOpcionesLayout.setHorizontalGroup(
            panelCancelarReservaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCancelarReservaOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnCancelarReservaAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(bttnCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCancelarReservaOpcionesLayout.setVerticalGroup(
            panelCancelarReservaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarReservaOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCancelarReservaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnCancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCancelarReservaAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCancelarReservaPrincipal.add(panelCancelarReservaOpciones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelCancelarReservaLayout = new javax.swing.GroupLayout(panelCancelarReserva);
        panelCancelarReserva.setLayout(panelCancelarReservaLayout);
        panelCancelarReservaLayout.setHorizontalGroup(
            panelCancelarReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCancelarReservaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCancelarReservaLayout.setVerticalGroup(
            panelCancelarReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCancelarReservaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCancelarReservaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarReservaBuscarActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) tableCancelarReservaReservasPendientes.getModel();
        tableModel.setRowCount(0);
        tableCancelarReservaReservasPendientes.setModel(tableModel);
        
        String dni_cliente = fieldCancelarReservaDNICliente.getText();
        if (dni_cliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduzca un DNI del cliente", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList reservasPendienteUsuario = recepcionista.consultarReservasPendientes(dni_cliente);
            if (reservasPendienteUsuario.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna reserva pendiente con dicho DNI del cliente", "Informacion", JOptionPane.ERROR_MESSAGE);
            } else {

                for (Object reservaPendiente : reservasPendienteUsuario) {

                    String cadena = reservaPendiente.toString();

                    String[] tokenizer = cadena.split(":");

                    tableModel.addRow(new Object[]{
                        tokenizer[0],
                        tokenizer[1],
                        tokenizer[2],
                        tokenizer[3],
                        tokenizer[4],
                        tokenizer[5],
                        reservaPendiente
                    });
                }
            }
        }
    }//GEN-LAST:event_bttnCancelarReservaBuscarActionPerformed

    private void bttnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarReservaActionPerformed
        int filas = tableCancelarReservaReservasPendientes.getModel().getRowCount();
        if (filas == 0) {
            JOptionPane.showMessageDialog(this, "Primero busque el DNI del cliente", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            int seleccionadas = tableCancelarReservaReservasPendientes.getSelectedRowCount();
            if (seleccionadas == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione una reserva pendiente del listado", "Informacion", JOptionPane.ERROR_MESSAGE);
            } else {
                int indice_fila = tableCancelarReservaReservasPendientes.getSelectedRow();

                Object reservaPendienteSeleccionada = tableCancelarReservaReservasPendientes.getValueAt(indice_fila, 6);

                DetallesCobro detalles = recepcionista.cancelarReserva(reservaPendienteSeleccionada);

                JOptionPane.showMessageDialog(this, "Reserva cancelada con éxito\nTarjeta Bancaria: " + detalles.tarjetaBancaria + "\nImporte a cobrar: " + detalles.importeCobro + " €", "Informacion", JOptionPane.INFORMATION_MESSAGE);

                dispose();
                VAnterior.setVisible(true);
            }
        }
    }//GEN-LAST:event_bttnCancelarReservaActionPerformed

    private void bttnCancelarReservaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarReservaAtrasActionPerformed
        dispose();
        VAnterior.setVisible(true);
    }//GEN-LAST:event_bttnCancelarReservaAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancelarReserva;
    private javax.swing.JButton bttnCancelarReservaAtras;
    private javax.swing.JButton bttnCancelarReservaBuscar;
    private javax.swing.JTextField fieldCancelarReservaDNICliente;
    private javax.swing.JPanel panelCancelarReserva;
    private javax.swing.JPanel panelCancelarReservaBttnBuscar;
    private javax.swing.JPanel panelCancelarReservaBuscarCliente;
    private javax.swing.JPanel panelCancelarReservaClienteDNI;
    private javax.swing.JPanel panelCancelarReservaListado;
    private javax.swing.JPanel panelCancelarReservaOpciones;
    private javax.swing.JPanel panelCancelarReservaPrincipal;
    private javax.swing.JPanel panelCancelarReservaPrincipalBuscarCliente;
    private javax.swing.JPanel panelCancelarReservaPrincipalListado;
    private javax.swing.JScrollPane scrollPaneCancelarReserva;
    private static javax.swing.JTable tableCancelarReservaReservasPendientes;
    // End of variables declaration//GEN-END:variables
    private JFrame VAnterior;
    private Recepcionista recepcionista;
}
