/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFrame;
import modelo.Propietario;

/**
 *
 * @author Pareja 3
 */
public class ConsultarGanancias extends JFrame {

    /**
     * Creates new form ConsultarGanancias
     * @param propietario
     * @param VAnterior
     */
    public ConsultarGanancias(Propietario propietario, JFrame VAnterior) {
        initComponents();

        this.propietario = propietario;
        this.VAnterior = VAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultarBeneficios = new javax.swing.JPanel();
        panelConsultarBeneficiosPrincipal = new javax.swing.JPanel();
        panelConsultarBeneficiosPrincipalListado = new javax.swing.JPanel();
        panelConsultarBeneficiosListado = new javax.swing.JPanel();
        panelConsultarBeneficiosBuscarMes = new javax.swing.JPanel();
        panelConsultarBeneficiosPrincipalBuscarMes = new javax.swing.JPanel();
        panelConsultarBeneficiosMes = new javax.swing.JPanel();
        labelConsultarBeneficiosTitulo = new javax.swing.JLabel();
        panelMesAnyoPrincipal = new javax.swing.JPanel();
        comboBoxBeneficiosMes = new javax.swing.JComboBox<>();
        comboBoxBeneficiosAnyo = new javax.swing.JComboBox<>();
        scrollPaneConsultarBeneficios = new javax.swing.JScrollPane();
        tableBeneficios = new javax.swing.JTable();
        panelConsultarBeneficiosTotalMesPrincipal = new javax.swing.JPanel();
        panelConsultarBeneficiosTotalMes = new javax.swing.JPanel();
        labelConsultarBeneficiosTotalMes = new javax.swing.JLabel();
        fieldConsultarBeneficiosTotalMes = new javax.swing.JTextField();
        panelConsultarBeneficiosOpciones = new javax.swing.JPanel();
        bttnConsultarBeneficiosAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 450));

        panelConsultarBeneficios.setBackground(new java.awt.Color(102, 102, 102));
        panelConsultarBeneficios.setPreferredSize(new java.awt.Dimension(500, 450));

        panelConsultarBeneficiosPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        panelConsultarBeneficiosPrincipal.setAlignmentX(0.0F);
        panelConsultarBeneficiosPrincipal.setAlignmentY(0.0F);
        panelConsultarBeneficiosPrincipal.setLayout(new java.awt.BorderLayout());

        panelConsultarBeneficiosPrincipalListado.setBackground(new java.awt.Color(153, 153, 153));
        panelConsultarBeneficiosPrincipalListado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelConsultarBeneficiosListado.setLayout(new java.awt.BorderLayout());

        panelConsultarBeneficiosBuscarMes.setBackground(new java.awt.Color(153, 153, 153));
        panelConsultarBeneficiosBuscarMes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelConsultarBeneficiosPrincipalBuscarMes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelConsultarBeneficiosPrincipalBuscarMes.setPreferredSize(new java.awt.Dimension(454, 73));
        panelConsultarBeneficiosPrincipalBuscarMes.setLayout(new java.awt.BorderLayout());

        panelConsultarBeneficiosMes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BENEFICIO EMPRESA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelConsultarBeneficiosMes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        labelConsultarBeneficiosTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelConsultarBeneficiosTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConsultarBeneficiosTitulo.setText("Seleccione un mes y año:");

        comboBoxBeneficiosMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        panelMesAnyoPrincipal.add(comboBoxBeneficiosMes);

        comboBoxBeneficiosAnyo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        panelMesAnyoPrincipal.add(comboBoxBeneficiosAnyo);

        javax.swing.GroupLayout panelConsultarBeneficiosMesLayout = new javax.swing.GroupLayout(panelConsultarBeneficiosMes);
        panelConsultarBeneficiosMes.setLayout(panelConsultarBeneficiosMesLayout);
        panelConsultarBeneficiosMesLayout.setHorizontalGroup(
            panelConsultarBeneficiosMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBeneficiosMesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarBeneficiosMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMesAnyoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelConsultarBeneficiosTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelConsultarBeneficiosMesLayout.setVerticalGroup(
            panelConsultarBeneficiosMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarBeneficiosMesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelConsultarBeneficiosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMesAnyoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelConsultarBeneficiosPrincipalBuscarMes.add(panelConsultarBeneficiosMes, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelConsultarBeneficiosBuscarMesLayout = new javax.swing.GroupLayout(panelConsultarBeneficiosBuscarMes);
        panelConsultarBeneficiosBuscarMes.setLayout(panelConsultarBeneficiosBuscarMesLayout);
        panelConsultarBeneficiosBuscarMesLayout.setHorizontalGroup(
            panelConsultarBeneficiosBuscarMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultarBeneficiosPrincipalBuscarMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        panelConsultarBeneficiosBuscarMesLayout.setVerticalGroup(
            panelConsultarBeneficiosBuscarMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultarBeneficiosPrincipalBuscarMes, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        panelConsultarBeneficiosListado.add(panelConsultarBeneficiosBuscarMes, java.awt.BorderLayout.NORTH);

        scrollPaneConsultarBeneficios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableBeneficios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clientes", "Habitaciones", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBeneficios.getTableHeader().setReorderingAllowed(false);
        scrollPaneConsultarBeneficios.setViewportView(tableBeneficios);
        if (tableBeneficios.getColumnModel().getColumnCount() > 0) {
            tableBeneficios.getColumnModel().getColumn(0).setResizable(false);
            tableBeneficios.getColumnModel().getColumn(1).setResizable(false);
            tableBeneficios.getColumnModel().getColumn(2).setResizable(false);
        }

        panelConsultarBeneficiosListado.add(scrollPaneConsultarBeneficios, java.awt.BorderLayout.CENTER);

        panelConsultarBeneficiosTotalMesPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelConsultarBeneficiosTotalMes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelConsultarBeneficiosTotalMes.setText("Total (mes):");
        panelConsultarBeneficiosTotalMes.add(labelConsultarBeneficiosTotalMes);

        fieldConsultarBeneficiosTotalMes.setColumns(10);
        fieldConsultarBeneficiosTotalMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldConsultarBeneficiosTotalMes.setEnabled(false);
        panelConsultarBeneficiosTotalMes.add(fieldConsultarBeneficiosTotalMes);

        javax.swing.GroupLayout panelConsultarBeneficiosTotalMesPrincipalLayout = new javax.swing.GroupLayout(panelConsultarBeneficiosTotalMesPrincipal);
        panelConsultarBeneficiosTotalMesPrincipal.setLayout(panelConsultarBeneficiosTotalMesPrincipalLayout);
        panelConsultarBeneficiosTotalMesPrincipalLayout.setHorizontalGroup(
            panelConsultarBeneficiosTotalMesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarBeneficiosTotalMesPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultarBeneficiosTotalMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultarBeneficiosTotalMesPrincipalLayout.setVerticalGroup(
            panelConsultarBeneficiosTotalMesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBeneficiosTotalMesPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultarBeneficiosTotalMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelConsultarBeneficiosListado.add(panelConsultarBeneficiosTotalMesPrincipal, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelConsultarBeneficiosPrincipalListadoLayout = new javax.swing.GroupLayout(panelConsultarBeneficiosPrincipalListado);
        panelConsultarBeneficiosPrincipalListado.setLayout(panelConsultarBeneficiosPrincipalListadoLayout);
        panelConsultarBeneficiosPrincipalListadoLayout.setHorizontalGroup(
            panelConsultarBeneficiosPrincipalListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBeneficiosPrincipalListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultarBeneficiosListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultarBeneficiosPrincipalListadoLayout.setVerticalGroup(
            panelConsultarBeneficiosPrincipalListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBeneficiosPrincipalListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultarBeneficiosListado, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConsultarBeneficiosPrincipal.add(panelConsultarBeneficiosPrincipalListado, java.awt.BorderLayout.CENTER);

        panelConsultarBeneficiosOpciones.setBackground(new java.awt.Color(153, 153, 153));
        panelConsultarBeneficiosOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnConsultarBeneficiosAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver_32.png"))); // NOI18N
        bttnConsultarBeneficiosAtras.setText("Atrás");
        bttnConsultarBeneficiosAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnConsultarBeneficiosAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConsultarBeneficiosAtrasActionPerformed(evt);
            }
        });
        panelConsultarBeneficiosOpciones.add(bttnConsultarBeneficiosAtras);

        panelConsultarBeneficiosPrincipal.add(panelConsultarBeneficiosOpciones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelConsultarBeneficiosLayout = new javax.swing.GroupLayout(panelConsultarBeneficios);
        panelConsultarBeneficios.setLayout(panelConsultarBeneficiosLayout);
        panelConsultarBeneficiosLayout.setHorizontalGroup(
            panelConsultarBeneficiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBeneficiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultarBeneficiosPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultarBeneficiosLayout.setVerticalGroup(
            panelConsultarBeneficiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarBeneficiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultarBeneficiosPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelConsultarBeneficios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelConsultarBeneficios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnConsultarBeneficiosAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConsultarBeneficiosAtrasActionPerformed
        dispose();
        VAnterior.setVisible(true);
    }//GEN-LAST:event_bttnConsultarBeneficiosAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnConsultarBeneficiosAtras;
    private javax.swing.JComboBox<String> comboBoxBeneficiosAnyo;
    private javax.swing.JComboBox<String> comboBoxBeneficiosMes;
    private javax.swing.JTextField fieldConsultarBeneficiosTotalMes;
    private javax.swing.JLabel labelConsultarBeneficiosTitulo;
    private javax.swing.JLabel labelConsultarBeneficiosTotalMes;
    private javax.swing.JPanel panelConsultarBeneficios;
    private javax.swing.JPanel panelConsultarBeneficiosBuscarMes;
    private javax.swing.JPanel panelConsultarBeneficiosListado;
    private javax.swing.JPanel panelConsultarBeneficiosMes;
    private javax.swing.JPanel panelConsultarBeneficiosOpciones;
    private javax.swing.JPanel panelConsultarBeneficiosPrincipal;
    private javax.swing.JPanel panelConsultarBeneficiosPrincipalBuscarMes;
    private javax.swing.JPanel panelConsultarBeneficiosPrincipalListado;
    private javax.swing.JPanel panelConsultarBeneficiosTotalMes;
    private javax.swing.JPanel panelConsultarBeneficiosTotalMesPrincipal;
    private javax.swing.JPanel panelMesAnyoPrincipal;
    private javax.swing.JScrollPane scrollPaneConsultarBeneficios;
    private static javax.swing.JTable tableBeneficios;
    // End of variables declaration//GEN-END:variables
    private Propietario propietario;
    private JFrame VAnterior;
}
