package vista;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.DetallesReserva;
import modelo.GestorEventos;
import modelo.GestorHotel;
import modelo.Personal;
import modelo.Propietario;
import modelo.Recepcionista;
import modelo.Supervisor;

public class HotelSweetDreamsGUI extends JFrame implements Observer {

    public HotelSweetDreamsGUI() {

        initComponents();

        setLocationRelativeTo(null);

        gestorHotel = new GestorHotel();
        GestorEventos.getInstance().suscribir(this, "AVISO_RESERVA_PENDIENTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelUsuarioClave = new javax.swing.JPanel();
        labelLoginUsuario = new javax.swing.JLabel();
        fieldLoginUsuario = new javax.swing.JTextField();
        labelLoginClave = new javax.swing.JLabel();
        fieldLoginClave = new javax.swing.JPasswordField();
        panelOpciones = new javax.swing.JPanel();
        bttnLoginSalir = new javax.swing.JButton();
        bttnLoginAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/hotel_beach_64.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(500, 350));

        panelSuperior.setBackground(new java.awt.Color(255, 204, 102));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Hotel Sweet Dreams");
        labelTitulo.setFocusCycleRoot(true);

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.setBackground(new java.awt.Color(255, 204, 102));
        panelCentral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        panelUsuarioClave.setBackground(new java.awt.Color(204, 204, 204));
        panelUsuarioClave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelUsuarioClave.setLayout(new java.awt.GridLayout(2, 2));

        labelLoginUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginUsuario.setText("Usuario:");
        panelUsuarioClave.add(labelLoginUsuario);

        fieldLoginUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelUsuarioClave.add(fieldLoginUsuario);

        labelLoginClave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginClave.setText("Contraseña:");
        panelUsuarioClave.add(labelLoginClave);

        fieldLoginClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelUsuarioClave.add(fieldLoginClave);

        panelOpciones.setBackground(new java.awt.Color(153, 153, 153));
        panelOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnLoginSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit_32.png"))); // NOI18N
        bttnLoginSalir.setToolTipText("Salir de la aplicación.");
        bttnLoginSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnLoginSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLoginSalirActionPerformed(evt);
            }
        });

        bttnLoginAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnLoginAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_32.png"))); // NOI18N
        bttnLoginAceptar.setText("Iniciar Sesión");
        bttnLoginAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnLoginAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLoginAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnLoginSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnLoginAceptar)
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnLoginSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnLoginAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUsuarioClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUsuarioClave, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnLoginSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLoginSalirActionPerformed
        gestorHotel.salir();
        System.exit(0);
    }//GEN-LAST:event_bttnLoginSalirActionPerformed

    private void bttnLoginAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLoginAceptarActionPerformed
        String usuario = fieldLoginUsuario.getText();
        String password = fieldLoginClave.getText();

        empleado = gestorHotel.login(usuario, password);

        if (empleado != null) {
            if (empleado.getClass().getSimpleName().equals(Recepcionista.class.getSimpleName())) {
                VentanaRecepcionista ventanaRecepcionista = new VentanaRecepcionista((Recepcionista) empleado, gestorHotel, this);
                ventanaRecepcionista.setLocationRelativeTo(null);
                ventanaRecepcionista.setVisible(true);
                setVisible(false);
            } else if (empleado.getClass().getSimpleName().equals(Supervisor.class.getSimpleName())) {
                VentanaSupervisor ventanaSupervisor = new VentanaSupervisor((Supervisor) empleado, gestorHotel, this);
                ventanaSupervisor.setLocationRelativeTo(null);
                ventanaSupervisor.setVisible(true);
                setVisible(false);
            } else if (empleado.getClass().getSimpleName().equals(Propietario.class.getSimpleName())) {
                VentanaPropietario ventanaPropietario = new VentanaPropietario((Propietario) empleado, this);
                ventanaPropietario.setLocationRelativeTo(null);
                ventanaPropietario.setVisible(true);
                setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecta", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        fieldLoginClave.setText("");
        fieldLoginUsuario.setText("");
    }//GEN-LAST:event_bttnLoginAceptarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        gestorHotel.salir();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing
    @Override
    public void update(Observable o, Object arg) {
        DetallesReserva detallesReserva = (DetallesReserva) arg;
        String info
                = "La reserva del cliente con DNI " + detallesReserva.getDNI() + " no se ha cumplido su plazo de entrada."
                + "\nDatos Reserva :\n"
                + "\tFecha de entrada : " + detallesReserva.getFech_ent() + "\n"
                + "\tImporte cobrado de una noche :" + detallesReserva.getImporte() + "€\n"
                + "\tNumero de dias : " + detallesReserva.getNum_dias() + "\n"
                + "\tCliente : " + detallesReserva.getNombre() + "\n"
                + "\tTelefono : " + detallesReserva.getTelefono() + "\n"
                + "\tDireccion : " + detallesReserva.getDireccion();

        JOptionPane.showMessageDialog(this, info,
                "Reserva Caducada", JOptionPane.WARNING_MESSAGE);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelSweetDreamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelSweetDreamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelSweetDreamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelSweetDreamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelSweetDreamsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnLoginAceptar;
    private javax.swing.JButton bttnLoginSalir;
    public javax.swing.JPasswordField fieldLoginClave;
    public javax.swing.JTextField fieldLoginUsuario;
    private javax.swing.JLabel labelLoginClave;
    private javax.swing.JLabel labelLoginUsuario;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelUsuarioClave;
    // End of variables declaration//GEN-END:variables
    private GestorHotel gestorHotel;
    private Personal empleado;
}
