/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Supervisor;

/**
 *
 * @author Pareja 3
 */
public class ModificarDescuentos extends JFrame {

    /**
     * Creates new form ModificarDescuentos
     *
     * @param supervisor
     * @param VAnterior
     */
    public ModificarDescuentos(Supervisor supervisor, JFrame VAnterior) {
        initComponents();

        this.supervisor = supervisor;
        this.VAnterior = VAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescuentos = new javax.swing.JPanel();
        panelDescuentosPrincipal = new javax.swing.JPanel();
        panelDescuentosContenido = new javax.swing.JPanel();
        panelDescuentosPrincipalCuerpo = new javax.swing.JPanel();
        panelDescuentosTitulo = new javax.swing.JPanel();
        labelDescuentosTitulo = new javax.swing.JLabel();
        panelDescuentosCuerpo = new javax.swing.JPanel();
        panelDescuentosTipos = new javax.swing.JPanel();
        labelDescuentosActual = new javax.swing.JLabel();
        fieldDescuentosActual = new javax.swing.JTextField();
        labelDescuentosModificacion = new javax.swing.JLabel();
        fieldDescuentosModificacion = new javax.swing.JTextField();
        panelDescuentosOpciones = new javax.swing.JPanel();
        bttnDescuentosAplicar = new javax.swing.JButton();
        bttnDescuentosAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(502, 280));

        panelDescuentos.setBackground(new java.awt.Color(102, 102, 102));
        panelDescuentos.setPreferredSize(new java.awt.Dimension(502, 280));

        panelDescuentosPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        panelDescuentosPrincipal.setAlignmentX(0.0F);
        panelDescuentosPrincipal.setAlignmentY(0.0F);
        panelDescuentosPrincipal.setLayout(new java.awt.BorderLayout());

        panelDescuentosContenido.setBackground(new java.awt.Color(153, 153, 153));
        panelDescuentosContenido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelDescuentosPrincipalCuerpo.setLayout(new java.awt.BorderLayout());

        panelDescuentosTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDescuentosTitulo.setPreferredSize(new java.awt.Dimension(454, 73));
        panelDescuentosTitulo.setLayout(new java.awt.BorderLayout());

        labelDescuentosTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDescuentosTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescuentosTitulo.setText("MODIFICAR DESCUENTO");
        panelDescuentosTitulo.add(labelDescuentosTitulo, java.awt.BorderLayout.CENTER);

        panelDescuentosPrincipalCuerpo.add(panelDescuentosTitulo, java.awt.BorderLayout.NORTH);

        panelDescuentosTipos.setLayout(new java.awt.GridLayout(2, 2, 10, 15));

        labelDescuentosActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescuentosActual.setText("Actual Descuento:");
        panelDescuentosTipos.add(labelDescuentosActual);

        fieldDescuentosActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldDescuentosActual.setText("10%");
        fieldDescuentosActual.setEnabled(false);
        panelDescuentosTipos.add(fieldDescuentosActual);

        labelDescuentosModificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescuentosModificacion.setText("Nuevo Descuento:");
        panelDescuentosTipos.add(labelDescuentosModificacion);

        fieldDescuentosModificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelDescuentosTipos.add(fieldDescuentosModificacion);

        javax.swing.GroupLayout panelDescuentosCuerpoLayout = new javax.swing.GroupLayout(panelDescuentosCuerpo);
        panelDescuentosCuerpo.setLayout(panelDescuentosCuerpoLayout);
        panelDescuentosCuerpoLayout.setHorizontalGroup(
            panelDescuentosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDescuentosCuerpoLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(panelDescuentosTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panelDescuentosCuerpoLayout.setVerticalGroup(
            panelDescuentosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDescuentosCuerpoLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(panelDescuentosTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelDescuentosPrincipalCuerpo.add(panelDescuentosCuerpo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelDescuentosContenidoLayout = new javax.swing.GroupLayout(panelDescuentosContenido);
        panelDescuentosContenido.setLayout(panelDescuentosContenidoLayout);
        panelDescuentosContenidoLayout.setHorizontalGroup(
            panelDescuentosContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescuentosContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescuentosPrincipalCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDescuentosContenidoLayout.setVerticalGroup(
            panelDescuentosContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescuentosContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescuentosPrincipalCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelDescuentosPrincipal.add(panelDescuentosContenido, java.awt.BorderLayout.CENTER);

        panelDescuentosOpciones.setBackground(new java.awt.Color(153, 153, 153));
        panelDescuentosOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnDescuentosAplicar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnDescuentosAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar_32.png"))); // NOI18N
        bttnDescuentosAplicar.setText("Aplicar");
        bttnDescuentosAplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnDescuentosAplicar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bttnDescuentosAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDescuentosAplicarActionPerformed(evt);
            }
        });

        bttnDescuentosAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver_32.png"))); // NOI18N
        bttnDescuentosAtras.setText("Atrás");
        bttnDescuentosAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnDescuentosAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDescuentosAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDescuentosOpcionesLayout = new javax.swing.GroupLayout(panelDescuentosOpciones);
        panelDescuentosOpciones.setLayout(panelDescuentosOpcionesLayout);
        panelDescuentosOpcionesLayout.setHorizontalGroup(
            panelDescuentosOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDescuentosOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnDescuentosAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(bttnDescuentosAplicar)
                .addContainerGap())
        );
        panelDescuentosOpcionesLayout.setVerticalGroup(
            panelDescuentosOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescuentosOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescuentosOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnDescuentosAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnDescuentosAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDescuentosPrincipal.add(panelDescuentosOpciones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelDescuentosLayout = new javax.swing.GroupLayout(panelDescuentos);
        panelDescuentos.setLayout(panelDescuentosLayout);
        panelDescuentosLayout.setHorizontalGroup(
            panelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescuentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescuentosPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDescuentosLayout.setVerticalGroup(
            panelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescuentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescuentosPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDescuentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDescuentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnDescuentosAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDescuentosAplicarActionPerformed
        JOptionPane.showMessageDialog(this, "Se ha aplicado el descuento.", "Información", JOptionPane.INFORMATION_MESSAGE);

        dispose();
        VAnterior.setVisible(true);
    }//GEN-LAST:event_bttnDescuentosAplicarActionPerformed

    private void bttnDescuentosAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDescuentosAtrasActionPerformed
        dispose();
        VAnterior.setVisible(true);
    }//GEN-LAST:event_bttnDescuentosAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnDescuentosAplicar;
    private javax.swing.JButton bttnDescuentosAtras;
    private javax.swing.JTextField fieldDescuentosActual;
    private javax.swing.JTextField fieldDescuentosModificacion;
    private javax.swing.JLabel labelDescuentosActual;
    private javax.swing.JLabel labelDescuentosModificacion;
    private javax.swing.JLabel labelDescuentosTitulo;
    private javax.swing.JPanel panelDescuentos;
    private javax.swing.JPanel panelDescuentosContenido;
    private javax.swing.JPanel panelDescuentosCuerpo;
    private javax.swing.JPanel panelDescuentosOpciones;
    private javax.swing.JPanel panelDescuentosPrincipal;
    private javax.swing.JPanel panelDescuentosPrincipalCuerpo;
    private javax.swing.JPanel panelDescuentosTipos;
    private javax.swing.JPanel panelDescuentosTitulo;
    // End of variables declaration//GEN-END:variables
    private Supervisor supervisor;
    private JFrame VAnterior;
}
