/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Recepcionista;

/**
 *
 * @author Pareja 2
 */
public class RealizarCheckIn extends JFrame {

    /**
     * Creates new form RealizarCheckIn
     *
     * @param recepcionista
     * @param VAnterior
     */
    public RealizarCheckIn(Recepcionista recepcionista, JFrame VAnterior) {
        initComponents();

        this.recepcionista = recepcionista;
        this.VAnterior = VAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCheckIn = new javax.swing.JPanel();
        panelCheckInPrincipal = new javax.swing.JPanel();
        panelCheckInPrincipalListado = new javax.swing.JPanel();
        panelCheckInListado = new javax.swing.JPanel();
        panelCheckInBuscarCliente = new javax.swing.JPanel();
        panelCheckInPrincipalBuscarCliente = new javax.swing.JPanel();
        panelCheckInClienteDNI = new javax.swing.JPanel();
        fieldCheckInDNICliente = new javax.swing.JTextField();
        panelCheckInBttnBuscar = new javax.swing.JPanel();
        bttnCheckInBuscar = new javax.swing.JButton();
        scrollPaneCheckInReservasPendientes = new javax.swing.JScrollPane();
        tableCheckInReservasPendientes = new javax.swing.JTable();
        panelCheckInOpciones = new javax.swing.JPanel();
        bttnCheckInRealizarCheckIn = new javax.swing.JButton();
        bttnCheckInAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 350));
        setSize(new java.awt.Dimension(500, 350));

        panelCheckIn.setBackground(new java.awt.Color(102, 102, 102));
        panelCheckIn.setPreferredSize(new java.awt.Dimension(500, 350));

        panelCheckInPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        panelCheckInPrincipal.setAlignmentX(0.0F);
        panelCheckInPrincipal.setAlignmentY(0.0F);
        panelCheckInPrincipal.setLayout(new java.awt.BorderLayout());

        panelCheckInPrincipalListado.setBackground(new java.awt.Color(153, 153, 153));
        panelCheckInPrincipalListado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelCheckInListado.setLayout(new java.awt.BorderLayout());

        panelCheckInBuscarCliente.setBackground(new java.awt.Color(153, 153, 153));
        panelCheckInBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelCheckInPrincipalBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCheckInPrincipalBuscarCliente.setPreferredSize(new java.awt.Dimension(454, 73));
        panelCheckInPrincipalBuscarCliente.setLayout(new java.awt.BorderLayout());

        panelCheckInClienteDNI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelCheckInClienteDNI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelCheckInClienteDNI.setLayout(new java.awt.BorderLayout());

        fieldCheckInDNICliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldCheckInDNICliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelCheckInClienteDNI.add(fieldCheckInDNICliente, java.awt.BorderLayout.CENTER);

        panelCheckInPrincipalBuscarCliente.add(panelCheckInClienteDNI, java.awt.BorderLayout.CENTER);

        bttnCheckInBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnCheckInBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_32.png"))); // NOI18N
        bttnCheckInBuscar.setText("BUSCAR");
        bttnCheckInBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnCheckInBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttnCheckInBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCheckInBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCheckInBttnBuscarLayout = new javax.swing.GroupLayout(panelCheckInBttnBuscar);
        panelCheckInBttnBuscar.setLayout(panelCheckInBttnBuscarLayout);
        panelCheckInBttnBuscarLayout.setHorizontalGroup(
            panelCheckInBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
            .addGroup(panelCheckInBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCheckInBttnBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bttnCheckInBuscar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelCheckInBttnBuscarLayout.setVerticalGroup(
            panelCheckInBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(panelCheckInBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCheckInBttnBuscarLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(bttnCheckInBuscar)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        panelCheckInPrincipalBuscarCliente.add(panelCheckInBttnBuscar, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout panelCheckInBuscarClienteLayout = new javax.swing.GroupLayout(panelCheckInBuscarCliente);
        panelCheckInBuscarCliente.setLayout(panelCheckInBuscarClienteLayout);
        panelCheckInBuscarClienteLayout.setHorizontalGroup(
            panelCheckInBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCheckInPrincipalBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        panelCheckInBuscarClienteLayout.setVerticalGroup(
            panelCheckInBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCheckInPrincipalBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        panelCheckInListado.add(panelCheckInBuscarCliente, java.awt.BorderLayout.NORTH);

        tableCheckInReservasPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habitacion", "DNI", "Nombre", "Dias", "Importe", "Estado", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCheckInReservasPendientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCheckInReservasPendientes.getTableHeader().setReorderingAllowed(false);
        scrollPaneCheckInReservasPendientes.setViewportView(tableCheckInReservasPendientes);
        if (tableCheckInReservasPendientes.getColumnModel().getColumnCount() > 0) {
            tableCheckInReservasPendientes.getColumnModel().getColumn(0).setResizable(false);
            tableCheckInReservasPendientes.getColumnModel().getColumn(1).setResizable(false);
            tableCheckInReservasPendientes.getColumnModel().getColumn(2).setResizable(false);
            tableCheckInReservasPendientes.getColumnModel().getColumn(3).setResizable(false);
            tableCheckInReservasPendientes.getColumnModel().getColumn(4).setResizable(false);
            tableCheckInReservasPendientes.getColumnModel().getColumn(5).setResizable(false);
            tableCheckInReservasPendientes.getColumnModel().getColumn(6).setResizable(false);
            tableCheckInReservasPendientes.getColumnModel().getColumn(6).setPreferredWidth(0);
        }

        panelCheckInListado.add(scrollPaneCheckInReservasPendientes, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelCheckInPrincipalListadoLayout = new javax.swing.GroupLayout(panelCheckInPrincipalListado);
        panelCheckInPrincipalListado.setLayout(panelCheckInPrincipalListadoLayout);
        panelCheckInPrincipalListadoLayout.setHorizontalGroup(
            panelCheckInPrincipalListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckInPrincipalListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCheckInListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCheckInPrincipalListadoLayout.setVerticalGroup(
            panelCheckInPrincipalListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckInPrincipalListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCheckInListado, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCheckInPrincipal.add(panelCheckInPrincipalListado, java.awt.BorderLayout.CENTER);

        panelCheckInOpciones.setBackground(new java.awt.Color(153, 153, 153));
        panelCheckInOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnCheckInRealizarCheckIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnCheckInRealizarCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkin_32.png"))); // NOI18N
        bttnCheckInRealizarCheckIn.setText("Realizar CheckIn");
        bttnCheckInRealizarCheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnCheckInRealizarCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCheckInRealizarCheckInActionPerformed(evt);
            }
        });

        bttnCheckInAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver_32.png"))); // NOI18N
        bttnCheckInAtras.setText("Atrás");
        bttnCheckInAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnCheckInAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCheckInAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCheckInOpcionesLayout = new javax.swing.GroupLayout(panelCheckInOpciones);
        panelCheckInOpciones.setLayout(panelCheckInOpcionesLayout);
        panelCheckInOpcionesLayout.setHorizontalGroup(
            panelCheckInOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCheckInOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnCheckInAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(bttnCheckInRealizarCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCheckInOpcionesLayout.setVerticalGroup(
            panelCheckInOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckInOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCheckInOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnCheckInRealizarCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCheckInAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCheckInPrincipal.add(panelCheckInOpciones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelCheckInLayout = new javax.swing.GroupLayout(panelCheckIn);
        panelCheckIn.setLayout(panelCheckInLayout);
        panelCheckInLayout.setHorizontalGroup(
            panelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCheckInPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCheckInLayout.setVerticalGroup(
            panelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCheckInPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCheckInBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCheckInBuscarActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) tableCheckInReservasPendientes.getModel();
        tableModel.setRowCount(0);
        tableCheckInReservasPendientes.setModel(tableModel);

        String dni_cliente = fieldCheckInDNICliente.getText();
        if (dni_cliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduzca un DNI del cliente", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList reservasPendienteUsuario = recepcionista.consultarReservasPendientes(dni_cliente);
            if (reservasPendienteUsuario.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna reserva pendiente con dicho DNI del cliente", "Informacion", JOptionPane.ERROR_MESSAGE);
            } else {

                for (Object reservaPendiente : reservasPendienteUsuario) {

                    String cadena = reservaPendiente.toString();

                    String[] tokenizer = cadena.split(":");

                    tableModel.addRow(new Object[]{
                        tokenizer[0],
                        tokenizer[1],
                        tokenizer[2],
                        tokenizer[3],
                        tokenizer[4],
                        tokenizer[5],
                        reservaPendiente
                    });
                }
            }
        }
    }//GEN-LAST:event_bttnCheckInBuscarActionPerformed

    private void bttnCheckInRealizarCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCheckInRealizarCheckInActionPerformed
        int filas = tableCheckInReservasPendientes.getModel().getRowCount();
        if (filas == 0) {
            JOptionPane.showMessageDialog(this, "Primero busque el DNI del cliente", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            int seleccionadas = tableCheckInReservasPendientes.getSelectedRowCount();
            if (seleccionadas == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione una reserva pendiente del listado", "Informacion", JOptionPane.ERROR_MESSAGE);
            } else {
                int indice_fila = tableCheckInReservasPendientes.getSelectedRow();

                Object reservaPendienteSeleccionada = tableCheckInReservasPendientes.getValueAt(indice_fila, 6);

                int numeroHabitacion = recepcionista.realizarCheckIn(reservaPendienteSeleccionada);

                JOptionPane.showMessageDialog(this, "CheckIn realizado con éxito\nHabitacion: " + numeroHabitacion, "Informacion", JOptionPane.INFORMATION_MESSAGE);

                dispose();
                VAnterior.setVisible(true);
            }
        }
    }//GEN-LAST:event_bttnCheckInRealizarCheckInActionPerformed

    private void bttnCheckInAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCheckInAtrasActionPerformed
        dispose();
        VAnterior.setVisible(true);
    }//GEN-LAST:event_bttnCheckInAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCheckInAtras;
    private javax.swing.JButton bttnCheckInBuscar;
    private javax.swing.JButton bttnCheckInRealizarCheckIn;
    private javax.swing.JTextField fieldCheckInDNICliente;
    private javax.swing.JPanel panelCheckIn;
    private javax.swing.JPanel panelCheckInBttnBuscar;
    private javax.swing.JPanel panelCheckInBuscarCliente;
    private javax.swing.JPanel panelCheckInClienteDNI;
    private javax.swing.JPanel panelCheckInListado;
    private javax.swing.JPanel panelCheckInOpciones;
    private javax.swing.JPanel panelCheckInPrincipal;
    private javax.swing.JPanel panelCheckInPrincipalBuscarCliente;
    private javax.swing.JPanel panelCheckInPrincipalListado;
    private javax.swing.JScrollPane scrollPaneCheckInReservasPendientes;
    private static javax.swing.JTable tableCheckInReservasPendientes;
    // End of variables declaration//GEN-END:variables
private Recepcionista recepcionista;
    private JFrame VAnterior;
}
