package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.DetallesClienteHabitual;
import modelo.Recepcionista;

/**
 *
 * @author Pareja 1
 */
public class ReservarHabitacion extends JFrame {

    /**
     * Creates new form ReservarHabitacion
     *
     * @param recepcionista
     * @param habitacion
     * @param VAnterior
     * @param VPrincipal
     */
    public ReservarHabitacion(Recepcionista recepcionista, Object habitacion, JFrame VAnterior, JFrame VPrincipal) {
        initComponents();

        this.recepcionista = recepcionista;
        this.habitacion = habitacion;
        this.VAnterior = VAnterior;
        this.VPrincipal = VPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoCliente = new javax.swing.ButtonGroup();
        buttonGroupCedeDatos = new javax.swing.ButtonGroup();
        panelReservarHabitacion = new javax.swing.JPanel();
        panelReservarHabitacionPrincipal = new javax.swing.JPanel();
        panelReservarHabitacionPrincipalContenido = new javax.swing.JPanel();
        panelReservarHabitacionFormulario = new javax.swing.JPanel();
        panelReservarHabitacionHabitualFormulario = new javax.swing.JPanel();
        panelReservarHabitacionContenidoFormulario = new javax.swing.JPanel();
        panelReservarHabitacionContenidoFormularioCuerpo = new javax.swing.JPanel();
        panelReservarHabitacionContenidoFormularioCuerpoPrincipal = new javax.swing.JPanel();
        panelBuscarClienteHabitual = new javax.swing.JPanel();
        panelPrincipalBuscarClienteHabitual = new javax.swing.JPanel();
        panelClienteHabitualDNI = new javax.swing.JPanel();
        fieldDNIClienteHabitual = new javax.swing.JTextField();
        panelClienteHabitualBttnBuscar = new javax.swing.JPanel();
        bttnClienteHabitualBuscar = new javax.swing.JButton();
        panelFormularioClienteDatosPersonales = new javax.swing.JPanel();
        panelFormularioClienteDatosPersonalesCuerpo = new javax.swing.JPanel();
        labelFormularioClienteDNI = new javax.swing.JLabel();
        fieldFormularioClienteDNI = new javax.swing.JTextField();
        labelFormularioClienteNombre = new javax.swing.JLabel();
        fieldFormularioClienteNombre = new javax.swing.JTextField();
        labelFormularioClienteApellidos = new javax.swing.JLabel();
        fieldFormularioClienteApellidos = new javax.swing.JTextField();
        labelFormularioClienteCorreo = new javax.swing.JLabel();
        fieldFormularioClienteCorreo = new javax.swing.JTextField();
        labelFormularioClienteDireccion = new javax.swing.JLabel();
        fieldFormularioClienteDireccion = new javax.swing.JTextField();
        labelFormularioClienteTelefono = new javax.swing.JLabel();
        fieldFormularioClienteTelefono = new javax.swing.JTextField();
        panelFormularioClienteTarjetaCredito = new javax.swing.JPanel();
        fieldFormularioClienteTarjetaCredito = new javax.swing.JTextField();
        panelFormularioClienteCedeDatos = new javax.swing.JPanel();
        panelFormularioClienteCedeDatosPrincipal = new javax.swing.JPanel();
        labelCedeDatosTitulo = new javax.swing.JLabel();
        panelCedeDatosOpciones = new javax.swing.JPanel();
        radioButtonFormularioClienteSiCede = new javax.swing.JRadioButton();
        radioButtonFormularioClienteNoCede = new javax.swing.JRadioButton();
        panelReservarHabitacionOpciones = new javax.swing.JPanel();
        bttnReservarHabitacionConfirmarReservar = new javax.swing.JButton();
        bttnReservarHabitacionlAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 761));

        panelReservarHabitacion.setBackground(new java.awt.Color(102, 102, 102));
        panelReservarHabitacion.setPreferredSize(new java.awt.Dimension(500, 761));

        panelReservarHabitacionPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        panelReservarHabitacionPrincipal.setAlignmentX(0.0F);
        panelReservarHabitacionPrincipal.setAlignmentY(0.0F);
        panelReservarHabitacionPrincipal.setLayout(new java.awt.BorderLayout());

        panelReservarHabitacionPrincipalContenido.setBackground(new java.awt.Color(153, 153, 153));
        panelReservarHabitacionPrincipalContenido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelReservarHabitacionFormulario.setBackground(new java.awt.Color(153, 153, 153));

        panelReservarHabitacionHabitualFormulario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelReservarHabitacionContenidoFormulario.setLayout(new java.awt.BorderLayout());

        panelBuscarClienteHabitual.setBackground(new java.awt.Color(153, 153, 153));
        panelBuscarClienteHabitual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBuscarClienteHabitual.setPreferredSize(new java.awt.Dimension(454, 73));

        panelPrincipalBuscarClienteHabitual.setBackground(new java.awt.Color(102, 102, 102));
        panelPrincipalBuscarClienteHabitual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPrincipalBuscarClienteHabitual.setPreferredSize(new java.awt.Dimension(454, 73));
        panelPrincipalBuscarClienteHabitual.setLayout(new java.awt.BorderLayout());

        panelClienteHabitualDNI.setBackground(new java.awt.Color(102, 102, 102));
        panelClienteHabitualDNI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI Cliente Habitual", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelClienteHabitualDNI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        fieldDNIClienteHabitual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldDNIClienteHabitual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelClienteHabitualDNILayout = new javax.swing.GroupLayout(panelClienteHabitualDNI);
        panelClienteHabitualDNI.setLayout(panelClienteHabitualDNILayout);
        panelClienteHabitualDNILayout.setHorizontalGroup(
            panelClienteHabitualDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteHabitualDNILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldDNIClienteHabitual, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClienteHabitualDNILayout.setVerticalGroup(
            panelClienteHabitualDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteHabitualDNILayout.createSequentialGroup()
                .addComponent(fieldDNIClienteHabitual, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPrincipalBuscarClienteHabitual.add(panelClienteHabitualDNI, java.awt.BorderLayout.CENTER);

        panelClienteHabitualBttnBuscar.setBackground(new java.awt.Color(102, 102, 102));

        bttnClienteHabitualBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnClienteHabitualBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_32.png"))); // NOI18N
        bttnClienteHabitualBuscar.setText("BUSCAR");
        bttnClienteHabitualBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnClienteHabitualBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttnClienteHabitualBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClienteHabitualBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClienteHabitualBttnBuscarLayout = new javax.swing.GroupLayout(panelClienteHabitualBttnBuscar);
        panelClienteHabitualBttnBuscar.setLayout(panelClienteHabitualBttnBuscarLayout);
        panelClienteHabitualBttnBuscarLayout.setHorizontalGroup(
            panelClienteHabitualBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteHabitualBttnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnClienteHabitualBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteHabitualBttnBuscarLayout.setVerticalGroup(
            panelClienteHabitualBttnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteHabitualBttnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnClienteHabitualBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPrincipalBuscarClienteHabitual.add(panelClienteHabitualBttnBuscar, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout panelBuscarClienteHabitualLayout = new javax.swing.GroupLayout(panelBuscarClienteHabitual);
        panelBuscarClienteHabitual.setLayout(panelBuscarClienteHabitualLayout);
        panelBuscarClienteHabitualLayout.setHorizontalGroup(
            panelBuscarClienteHabitualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalBuscarClienteHabitual, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelBuscarClienteHabitualLayout.setVerticalGroup(
            panelBuscarClienteHabitualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteHabitualLayout.createSequentialGroup()
                .addComponent(panelPrincipalBuscarClienteHabitual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelFormularioClienteDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        panelFormularioClienteDatosPersonalesCuerpo.setLayout(new java.awt.GridLayout(6, 2, 0, 10));

        labelFormularioClienteDNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormularioClienteDNI.setText("DNI:");
        panelFormularioClienteDatosPersonalesCuerpo.add(labelFormularioClienteDNI);

        fieldFormularioClienteDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelFormularioClienteDatosPersonalesCuerpo.add(fieldFormularioClienteDNI);

        labelFormularioClienteNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormularioClienteNombre.setText("Nombre:");
        panelFormularioClienteDatosPersonalesCuerpo.add(labelFormularioClienteNombre);

        fieldFormularioClienteNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelFormularioClienteDatosPersonalesCuerpo.add(fieldFormularioClienteNombre);

        labelFormularioClienteApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormularioClienteApellidos.setText("Apellidos:");
        panelFormularioClienteDatosPersonalesCuerpo.add(labelFormularioClienteApellidos);

        fieldFormularioClienteApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelFormularioClienteDatosPersonalesCuerpo.add(fieldFormularioClienteApellidos);

        labelFormularioClienteCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormularioClienteCorreo.setText("Correo:");
        panelFormularioClienteDatosPersonalesCuerpo.add(labelFormularioClienteCorreo);

        fieldFormularioClienteCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelFormularioClienteDatosPersonalesCuerpo.add(fieldFormularioClienteCorreo);

        labelFormularioClienteDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormularioClienteDireccion.setText("Dirección:");
        panelFormularioClienteDatosPersonalesCuerpo.add(labelFormularioClienteDireccion);

        fieldFormularioClienteDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelFormularioClienteDatosPersonalesCuerpo.add(fieldFormularioClienteDireccion);

        labelFormularioClienteTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormularioClienteTelefono.setText("Teléfono:");
        panelFormularioClienteDatosPersonalesCuerpo.add(labelFormularioClienteTelefono);

        fieldFormularioClienteTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelFormularioClienteDatosPersonalesCuerpo.add(fieldFormularioClienteTelefono);

        javax.swing.GroupLayout panelFormularioClienteDatosPersonalesLayout = new javax.swing.GroupLayout(panelFormularioClienteDatosPersonales);
        panelFormularioClienteDatosPersonales.setLayout(panelFormularioClienteDatosPersonalesLayout);
        panelFormularioClienteDatosPersonalesLayout.setHorizontalGroup(
            panelFormularioClienteDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioClienteDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormularioClienteDatosPersonalesCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFormularioClienteDatosPersonalesLayout.setVerticalGroup(
            panelFormularioClienteDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioClienteDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormularioClienteDatosPersonalesCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelFormularioClienteTarjetaCredito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TARJETA DE CREDITO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        fieldFormularioClienteTarjetaCredito.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelFormularioClienteTarjetaCreditoLayout = new javax.swing.GroupLayout(panelFormularioClienteTarjetaCredito);
        panelFormularioClienteTarjetaCredito.setLayout(panelFormularioClienteTarjetaCreditoLayout);
        panelFormularioClienteTarjetaCreditoLayout.setHorizontalGroup(
            panelFormularioClienteTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelFormularioClienteTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFormularioClienteTarjetaCreditoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fieldFormularioClienteTarjetaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelFormularioClienteTarjetaCreditoLayout.setVerticalGroup(
            panelFormularioClienteTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(panelFormularioClienteTarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioClienteTarjetaCreditoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fieldFormularioClienteTarjetaCredito)
                    .addContainerGap()))
        );

        panelFormularioClienteCedeDatos.setBackground(new java.awt.Color(102, 102, 102));
        panelFormularioClienteCedeDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelFormularioClienteCedeDatosPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelCedeDatosTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCedeDatosTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCedeDatosTitulo.setText("Cede sus datos:");

        buttonGroupCedeDatos.add(radioButtonFormularioClienteSiCede);
        radioButtonFormularioClienteSiCede.setText("SI");
        panelCedeDatosOpciones.add(radioButtonFormularioClienteSiCede);

        buttonGroupCedeDatos.add(radioButtonFormularioClienteNoCede);
        radioButtonFormularioClienteNoCede.setSelected(true);
        radioButtonFormularioClienteNoCede.setText("NO");
        panelCedeDatosOpciones.add(radioButtonFormularioClienteNoCede);

        javax.swing.GroupLayout panelFormularioClienteCedeDatosPrincipalLayout = new javax.swing.GroupLayout(panelFormularioClienteCedeDatosPrincipal);
        panelFormularioClienteCedeDatosPrincipal.setLayout(panelFormularioClienteCedeDatosPrincipalLayout);
        panelFormularioClienteCedeDatosPrincipalLayout.setHorizontalGroup(
            panelFormularioClienteCedeDatosPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCedeDatosTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
            .addGroup(panelFormularioClienteCedeDatosPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCedeDatosOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );
        panelFormularioClienteCedeDatosPrincipalLayout.setVerticalGroup(
            panelFormularioClienteCedeDatosPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioClienteCedeDatosPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCedeDatosTitulo)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(panelFormularioClienteCedeDatosPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioClienteCedeDatosPrincipalLayout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(panelCedeDatosOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelFormularioClienteCedeDatosLayout = new javax.swing.GroupLayout(panelFormularioClienteCedeDatos);
        panelFormularioClienteCedeDatos.setLayout(panelFormularioClienteCedeDatosLayout);
        panelFormularioClienteCedeDatosLayout.setHorizontalGroup(
            panelFormularioClienteCedeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioClienteCedeDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormularioClienteCedeDatosPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFormularioClienteCedeDatosLayout.setVerticalGroup(
            panelFormularioClienteCedeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioClienteCedeDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormularioClienteCedeDatosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout = new javax.swing.GroupLayout(panelReservarHabitacionContenidoFormularioCuerpoPrincipal);
        panelReservarHabitacionContenidoFormularioCuerpoPrincipal.setLayout(panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout);
        panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout.setHorizontalGroup(
            panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBuscarClienteHabitual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(panelFormularioClienteCedeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFormularioClienteTarjetaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFormularioClienteDatosPersonales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout.setVerticalGroup(
            panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionContenidoFormularioCuerpoPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelBuscarClienteHabitual, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelFormularioClienteDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelFormularioClienteTarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFormularioClienteCedeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelReservarHabitacionContenidoFormularioCuerpoLayout = new javax.swing.GroupLayout(panelReservarHabitacionContenidoFormularioCuerpo);
        panelReservarHabitacionContenidoFormularioCuerpo.setLayout(panelReservarHabitacionContenidoFormularioCuerpoLayout);
        panelReservarHabitacionContenidoFormularioCuerpoLayout.setHorizontalGroup(
            panelReservarHabitacionContenidoFormularioCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionContenidoFormularioCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionContenidoFormularioCuerpoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelReservarHabitacionContenidoFormularioCuerpoLayout.setVerticalGroup(
            panelReservarHabitacionContenidoFormularioCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservarHabitacionContenidoFormularioCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionContenidoFormularioCuerpoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelReservarHabitacionContenidoFormulario.add(panelReservarHabitacionContenidoFormularioCuerpo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelReservarHabitacionHabitualFormularioLayout = new javax.swing.GroupLayout(panelReservarHabitacionHabitualFormulario);
        panelReservarHabitacionHabitualFormulario.setLayout(panelReservarHabitacionHabitualFormularioLayout);
        panelReservarHabitacionHabitualFormularioLayout.setHorizontalGroup(
            panelReservarHabitacionHabitualFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
            .addGroup(panelReservarHabitacionHabitualFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelReservarHabitacionHabitualFormularioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelReservarHabitacionContenidoFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelReservarHabitacionHabitualFormularioLayout.setVerticalGroup(
            panelReservarHabitacionHabitualFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(panelReservarHabitacionHabitualFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservarHabitacionHabitualFormularioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelReservarHabitacionContenidoFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelReservarHabitacionFormularioLayout = new javax.swing.GroupLayout(panelReservarHabitacionFormulario);
        panelReservarHabitacionFormulario.setLayout(panelReservarHabitacionFormularioLayout);
        panelReservarHabitacionFormularioLayout.setHorizontalGroup(
            panelReservarHabitacionFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionHabitualFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelReservarHabitacionFormularioLayout.setVerticalGroup(
            panelReservarHabitacionFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservarHabitacionFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionHabitualFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelReservarHabitacionPrincipalContenidoLayout = new javax.swing.GroupLayout(panelReservarHabitacionPrincipalContenido);
        panelReservarHabitacionPrincipalContenido.setLayout(panelReservarHabitacionPrincipalContenidoLayout);
        panelReservarHabitacionPrincipalContenidoLayout.setHorizontalGroup(
            panelReservarHabitacionPrincipalContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionPrincipalContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelReservarHabitacionPrincipalContenidoLayout.setVerticalGroup(
            panelReservarHabitacionPrincipalContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionPrincipalContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelReservarHabitacionPrincipal.add(panelReservarHabitacionPrincipalContenido, java.awt.BorderLayout.CENTER);

        panelReservarHabitacionOpciones.setBackground(new java.awt.Color(153, 153, 153));
        panelReservarHabitacionOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnReservarHabitacionConfirmarReservar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnReservarHabitacionConfirmarReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listado_habitaciones_32.png"))); // NOI18N
        bttnReservarHabitacionConfirmarReservar.setText("Confirmar Reserva");
        bttnReservarHabitacionConfirmarReservar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnReservarHabitacionConfirmarReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReservarHabitacionConfirmarReservarActionPerformed(evt);
            }
        });

        bttnReservarHabitacionlAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver_32.png"))); // NOI18N
        bttnReservarHabitacionlAtras.setText("Atrás");
        bttnReservarHabitacionlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnReservarHabitacionlAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReservarHabitacionlAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReservarHabitacionOpcionesLayout = new javax.swing.GroupLayout(panelReservarHabitacionOpciones);
        panelReservarHabitacionOpciones.setLayout(panelReservarHabitacionOpcionesLayout);
        panelReservarHabitacionOpcionesLayout.setHorizontalGroup(
            panelReservarHabitacionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservarHabitacionOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnReservarHabitacionlAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(bttnReservarHabitacionConfirmarReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelReservarHabitacionOpcionesLayout.setVerticalGroup(
            panelReservarHabitacionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservarHabitacionOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnReservarHabitacionConfirmarReservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnReservarHabitacionlAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelReservarHabitacionPrincipal.add(panelReservarHabitacionOpciones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelReservarHabitacionLayout = new javax.swing.GroupLayout(panelReservarHabitacion);
        panelReservarHabitacion.setLayout(panelReservarHabitacionLayout);
        panelReservarHabitacionLayout.setHorizontalGroup(
            panelReservarHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelReservarHabitacionLayout.setVerticalGroup(
            panelReservarHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservarHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReservarHabitacionPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReservarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelReservarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnClienteHabitualBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClienteHabitualBuscarActionPerformed
        String dni_cliente = fieldDNIClienteHabitual.getText();
        if (dni_cliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduzca un DNI del cliente", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            DetallesClienteHabitual detallesClienteHabitual = recepcionista.buscarClienteHabitual(dni_cliente);

            if (detallesClienteHabitual != null) {
                fieldFormularioClienteDNI.setText(detallesClienteHabitual.DNI);
                fieldFormularioClienteDNI.setEnabled(false);

                fieldFormularioClienteNombre.setText(detallesClienteHabitual.nombre);
                fieldFormularioClienteNombre.setEnabled(false);

                fieldFormularioClienteApellidos.setText(detallesClienteHabitual.apellidos);
                fieldFormularioClienteApellidos.setEnabled(false);

                fieldFormularioClienteCorreo.setText(detallesClienteHabitual.correo);
                fieldFormularioClienteCorreo.setEnabled(false);

                fieldFormularioClienteDireccion.setText(detallesClienteHabitual.direccion);
                fieldFormularioClienteDireccion.setEnabled(false);

                fieldFormularioClienteTelefono.setText(detallesClienteHabitual.telefono);
                fieldFormularioClienteTelefono.setEnabled(false);

                radioButtonFormularioClienteNoCede.setSelected(false);
                radioButtonFormularioClienteNoCede.setEnabled(false);

                radioButtonFormularioClienteSiCede.setSelected(false);
                radioButtonFormularioClienteSiCede.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "DNI del cliente no encontrado", "Informacion", JOptionPane.ERROR_MESSAGE);
                fieldDNIClienteHabitual.setText("");
            }
        }
    }//GEN-LAST:event_bttnClienteHabitualBuscarActionPerformed

    private void bttnReservarHabitacionConfirmarReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnReservarHabitacionConfirmarReservarActionPerformed
        String tarjetaCredito = fieldFormularioClienteTarjetaCredito.getText();
        String DNI = fieldFormularioClienteDNI.getText();
        String nombre = fieldFormularioClienteNombre.getText();
        String apellidos = fieldFormularioClienteApellidos.getText();
        String direccion = fieldFormularioClienteDireccion.getText();
        String telefono = fieldFormularioClienteTelefono.getText();

        if (!fieldFormularioClienteDNI.isEnabled()) { //Implica que se ha encontrado un cliente Habitual
            recepcionista.reservarHabitacionClienteHabitual(habitacion, tarjetaCredito);
        } else if (radioButtonFormularioClienteSiCede.isSelected()) {
            String correo = fieldFormularioClienteCorreo.getText();
            recepcionista.reservarHabitacionNuevoClienteHabitual(habitacion, tarjetaCredito, DNI, nombre, apellidos, direccion, telefono, correo);
        } else if (radioButtonFormularioClienteNoCede.isSelected()) {
            recepcionista.reservarHabitacionCliente(habitacion, tarjetaCredito, DNI, nombre, apellidos, direccion, telefono);
        }
        JOptionPane.showMessageDialog(this, "Reserva realizada correctamente.", "INFO", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        VPrincipal.setVisible(true);
    }//GEN-LAST:event_bttnReservarHabitacionConfirmarReservarActionPerformed

    private void bttnReservarHabitacionlAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnReservarHabitacionlAtrasActionPerformed
        dispose();
        VAnterior.setVisible(true);
    }//GEN-LAST:event_bttnReservarHabitacionlAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnClienteHabitualBuscar;
    private javax.swing.JButton bttnReservarHabitacionConfirmarReservar;
    private javax.swing.JButton bttnReservarHabitacionlAtras;
    private javax.swing.ButtonGroup buttonGroupCedeDatos;
    private javax.swing.ButtonGroup buttonGroupTipoCliente;
    private javax.swing.JTextField fieldDNIClienteHabitual;
    private javax.swing.JTextField fieldFormularioClienteApellidos;
    private javax.swing.JTextField fieldFormularioClienteCorreo;
    private javax.swing.JTextField fieldFormularioClienteDNI;
    private javax.swing.JTextField fieldFormularioClienteDireccion;
    private javax.swing.JTextField fieldFormularioClienteNombre;
    private javax.swing.JTextField fieldFormularioClienteTarjetaCredito;
    private javax.swing.JTextField fieldFormularioClienteTelefono;
    private javax.swing.JLabel labelCedeDatosTitulo;
    private javax.swing.JLabel labelFormularioClienteApellidos;
    private javax.swing.JLabel labelFormularioClienteCorreo;
    private javax.swing.JLabel labelFormularioClienteDNI;
    private javax.swing.JLabel labelFormularioClienteDireccion;
    private javax.swing.JLabel labelFormularioClienteNombre;
    private javax.swing.JLabel labelFormularioClienteTelefono;
    private javax.swing.JPanel panelBuscarClienteHabitual;
    private javax.swing.JPanel panelCedeDatosOpciones;
    private javax.swing.JPanel panelClienteHabitualBttnBuscar;
    private javax.swing.JPanel panelClienteHabitualDNI;
    private javax.swing.JPanel panelFormularioClienteCedeDatos;
    private javax.swing.JPanel panelFormularioClienteCedeDatosPrincipal;
    private javax.swing.JPanel panelFormularioClienteDatosPersonales;
    private javax.swing.JPanel panelFormularioClienteDatosPersonalesCuerpo;
    private javax.swing.JPanel panelFormularioClienteTarjetaCredito;
    private javax.swing.JPanel panelPrincipalBuscarClienteHabitual;
    private javax.swing.JPanel panelReservarHabitacion;
    private javax.swing.JPanel panelReservarHabitacionContenidoFormulario;
    private javax.swing.JPanel panelReservarHabitacionContenidoFormularioCuerpo;
    private javax.swing.JPanel panelReservarHabitacionContenidoFormularioCuerpoPrincipal;
    private javax.swing.JPanel panelReservarHabitacionFormulario;
    private javax.swing.JPanel panelReservarHabitacionHabitualFormulario;
    private javax.swing.JPanel panelReservarHabitacionOpciones;
    private javax.swing.JPanel panelReservarHabitacionPrincipal;
    private javax.swing.JPanel panelReservarHabitacionPrincipalContenido;
    private javax.swing.JRadioButton radioButtonFormularioClienteNoCede;
    private javax.swing.JRadioButton radioButtonFormularioClienteSiCede;
    // End of variables declaration//GEN-END:variables
    private Recepcionista recepcionista;
    private Object habitacion;
    private JFrame VAnterior;
    private JFrame VPrincipal;
}
