package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.DetallesTarifas;
import modelo.GestorHotel;
import modelo.Supervisor;

public class VentanaSupervisor extends JFrame {
    
    public VentanaSupervisor(Supervisor supervisor, GestorHotel gestorHotel, JFrame VAnterior) {
        initComponents();
        this.VAnterior = VAnterior;
        this.supervisor = supervisor;
        this.gestorHotel = gestorHotel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSupervisor = new javax.swing.JPanel();
        panelPrincipalSupervisor = new javax.swing.JPanel();
        panelPrincipalSupervisorOperaciones = new javax.swing.JPanel();
        panelSupervisorOperaciones = new javax.swing.JPanel();
        bttnVentanaSupervisorConsultarListadoHabitaciones = new javax.swing.JButton();
        bttnVentanaSupervisorCancelarReserva = new javax.swing.JButton();
        bttnVentanaSupervisorRealizarCheckIn = new javax.swing.JButton();
        bttnVentanaSupervisorRealizarCheckOut = new javax.swing.JButton();
        bttnVentanaSupervisorDescuentos = new javax.swing.JButton();
        bttnVentanaSupervisorTarifas = new javax.swing.JButton();
        panelSupervisorOpcionCerrarSesion = new javax.swing.JPanel();
        bttnVentanaSupervisorCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL - SUPERVISORES");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/supervisor_64.png")).getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(500, 310));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelSupervisor.setBackground(new java.awt.Color(102, 102, 102));

        panelPrincipalSupervisor.setBackground(new java.awt.Color(102, 102, 102));
        panelPrincipalSupervisor.setAlignmentX(0.0F);
        panelPrincipalSupervisor.setAlignmentY(0.0F);
        panelPrincipalSupervisor.setLayout(new java.awt.BorderLayout());

        panelPrincipalSupervisorOperaciones.setBackground(new java.awt.Color(153, 153, 153));
        panelPrincipalSupervisorOperaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelSupervisorOperaciones.setLayout(new java.awt.GridLayout(3, 2, 1, 1));

        bttnVentanaSupervisorConsultarListadoHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listado_habitaciones_32.png"))); // NOI18N
        bttnVentanaSupervisorConsultarListadoHabitaciones.setText("Consultar Listado Habitaciones");
        bttnVentanaSupervisorConsultarListadoHabitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnVentanaSupervisorConsultarListadoHabitaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttnVentanaSupervisorConsultarListadoHabitaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttnVentanaSupervisorConsultarListadoHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVentanaSupervisorConsultarListadoHabitacionesActionPerformed(evt);
            }
        });
        panelSupervisorOperaciones.add(bttnVentanaSupervisorConsultarListadoHabitaciones);

        bttnVentanaSupervisorCancelarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_reserva_32.png"))); // NOI18N
        bttnVentanaSupervisorCancelarReserva.setText("Cancelar Reserva");
        bttnVentanaSupervisorCancelarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnVentanaSupervisorCancelarReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttnVentanaSupervisorCancelarReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttnVentanaSupervisorCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVentanaSupervisorCancelarReservaActionPerformed(evt);
            }
        });
        panelSupervisorOperaciones.add(bttnVentanaSupervisorCancelarReserva);

        bttnVentanaSupervisorRealizarCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkin_32.png"))); // NOI18N
        bttnVentanaSupervisorRealizarCheckIn.setText("Realizar CheckIn");
        bttnVentanaSupervisorRealizarCheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnVentanaSupervisorRealizarCheckIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttnVentanaSupervisorRealizarCheckIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttnVentanaSupervisorRealizarCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVentanaSupervisorRealizarCheckInActionPerformed(evt);
            }
        });
        panelSupervisorOperaciones.add(bttnVentanaSupervisorRealizarCheckIn);

        bttnVentanaSupervisorRealizarCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkout_32.png"))); // NOI18N
        bttnVentanaSupervisorRealizarCheckOut.setText("Realizar CheckOut");
        bttnVentanaSupervisorRealizarCheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnVentanaSupervisorRealizarCheckOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttnVentanaSupervisorRealizarCheckOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttnVentanaSupervisorRealizarCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVentanaSupervisorRealizarCheckOutActionPerformed(evt);
            }
        });
        panelSupervisorOperaciones.add(bttnVentanaSupervisorRealizarCheckOut);

        bttnVentanaSupervisorDescuentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descuentos_32.png"))); // NOI18N
        bttnVentanaSupervisorDescuentos.setText("Descuentos");
        bttnVentanaSupervisorDescuentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnVentanaSupervisorDescuentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttnVentanaSupervisorDescuentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttnVentanaSupervisorDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVentanaSupervisorDescuentosActionPerformed(evt);
            }
        });
        panelSupervisorOperaciones.add(bttnVentanaSupervisorDescuentos);

        bttnVentanaSupervisorTarifas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarifas_32.png"))); // NOI18N
        bttnVentanaSupervisorTarifas.setText("Tarifas");
        bttnVentanaSupervisorTarifas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnVentanaSupervisorTarifas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttnVentanaSupervisorTarifas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttnVentanaSupervisorTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVentanaSupervisorTarifasActionPerformed(evt);
            }
        });
        panelSupervisorOperaciones.add(bttnVentanaSupervisorTarifas);

        javax.swing.GroupLayout panelPrincipalSupervisorOperacionesLayout = new javax.swing.GroupLayout(panelPrincipalSupervisorOperaciones);
        panelPrincipalSupervisorOperaciones.setLayout(panelPrincipalSupervisorOperacionesLayout);
        panelPrincipalSupervisorOperacionesLayout.setHorizontalGroup(
            panelPrincipalSupervisorOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalSupervisorOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSupervisorOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrincipalSupervisorOperacionesLayout.setVerticalGroup(
            panelPrincipalSupervisorOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalSupervisorOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSupervisorOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPrincipalSupervisor.add(panelPrincipalSupervisorOperaciones, java.awt.BorderLayout.PAGE_START);

        panelSupervisorOpcionCerrarSesion.setBackground(new java.awt.Color(153, 153, 153));
        panelSupervisorOpcionCerrarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnVentanaSupervisorCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bttnVentanaSupervisorCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_32.png"))); // NOI18N
        bttnVentanaSupervisorCerrarSesion.setText("Cerrar Sesión");
        bttnVentanaSupervisorCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnVentanaSupervisorCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVentanaSupervisorCerrarSesionActionPerformed(evt);
            }
        });
        panelSupervisorOpcionCerrarSesion.add(bttnVentanaSupervisorCerrarSesion);

        panelPrincipalSupervisor.add(panelSupervisorOpcionCerrarSesion, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelSupervisorLayout = new javax.swing.GroupLayout(panelSupervisor);
        panelSupervisor.setLayout(panelSupervisorLayout);
        panelSupervisorLayout.setHorizontalGroup(
            panelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipalSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSupervisorLayout.setVerticalGroup(
            panelSupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipalSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnVentanaSupervisorConsultarListadoHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVentanaSupervisorConsultarListadoHabitacionesActionPerformed
        ConsultarHabitacionesDisponibles consultarHabitacionesDisponibles = new ConsultarHabitacionesDisponibles(supervisor, this);
        setVisible(false);
        consultarHabitacionesDisponibles.setLocationRelativeTo(null);
        consultarHabitacionesDisponibles.setVisible(true);
    }//GEN-LAST:event_bttnVentanaSupervisorConsultarListadoHabitacionesActionPerformed

    private void bttnVentanaSupervisorCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVentanaSupervisorCancelarReservaActionPerformed
        CancelarReserva cancelarReserva = new CancelarReserva(supervisor, this);
        setVisible(false);
        cancelarReserva.setLocationRelativeTo(null);
        cancelarReserva.setVisible(true);
    }//GEN-LAST:event_bttnVentanaSupervisorCancelarReservaActionPerformed

    private void bttnVentanaSupervisorRealizarCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVentanaSupervisorRealizarCheckInActionPerformed
        RealizarCheckIn realizarCheckIn = new RealizarCheckIn(supervisor, this);
        
        setVisible(false);
        realizarCheckIn.setLocationRelativeTo(null);
        realizarCheckIn.setVisible(true);
    }//GEN-LAST:event_bttnVentanaSupervisorRealizarCheckInActionPerformed

    private void bttnVentanaSupervisorRealizarCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVentanaSupervisorRealizarCheckOutActionPerformed
        RealizarCheckOut realizarCheckOut = new RealizarCheckOut(supervisor, this);
        
        setVisible(false);
        realizarCheckOut.setLocationRelativeTo(null);
        realizarCheckOut.setVisible(true);
    }//GEN-LAST:event_bttnVentanaSupervisorRealizarCheckOutActionPerformed

    private void bttnVentanaSupervisorDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVentanaSupervisorDescuentosActionPerformed
        ModificarDescuentos modificarDescuentos = new ModificarDescuentos(supervisor, this);
        
        setVisible(false);
        modificarDescuentos.setLocationRelativeTo(null);
        modificarDescuentos.setVisible(true);
    }//GEN-LAST:event_bttnVentanaSupervisorDescuentosActionPerformed

    private void bttnVentanaSupervisorTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVentanaSupervisorTarifasActionPerformed
        DetallesTarifas detallesTarifas = supervisor.consultarTarifas();
        JOptionPane.showMessageDialog(this, "FORMATO: "
                + "Debe ser un numero entero o con 1 decimal. EJ: 234, 123.5\n"
                + "ATENCION: campo en blanco implica que no se modifica dicho precio",
                "Información", JOptionPane.INFORMATION_MESSAGE);
        
        ModificarTarifas modificarTarifas = new ModificarTarifas(supervisor, detallesTarifas, this);
        
        setVisible(false);
        modificarTarifas.setLocationRelativeTo(null);
        modificarTarifas.setVisible(true);
    }//GEN-LAST:event_bttnVentanaSupervisorTarifasActionPerformed

    private void bttnVentanaSupervisorCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVentanaSupervisorCerrarSesionActionPerformed
        dispose();
        
        VAnterior.setVisible(true);
        VAnterior.setLocationRelativeTo(null);
    }//GEN-LAST:event_bttnVentanaSupervisorCerrarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        gestorHotel.salir();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnVentanaSupervisorCancelarReserva;
    private javax.swing.JButton bttnVentanaSupervisorCerrarSesion;
    private javax.swing.JButton bttnVentanaSupervisorConsultarListadoHabitaciones;
    private javax.swing.JButton bttnVentanaSupervisorDescuentos;
    private javax.swing.JButton bttnVentanaSupervisorRealizarCheckIn;
    private javax.swing.JButton bttnVentanaSupervisorRealizarCheckOut;
    private javax.swing.JButton bttnVentanaSupervisorTarifas;
    private javax.swing.JPanel panelPrincipalSupervisor;
    private javax.swing.JPanel panelPrincipalSupervisorOperaciones;
    private javax.swing.JPanel panelSupervisor;
    private javax.swing.JPanel panelSupervisorOpcionCerrarSesion;
    private javax.swing.JPanel panelSupervisorOperaciones;
    // End of variables declaration//GEN-END:variables
    private Supervisor supervisor;
    private JFrame VAnterior;
    private GestorHotel gestorHotel;
}
